#服务配置
server:
  port: 9000
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-company #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 8
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
  #邮件
  mail:
    host: smtp.qq.com # 服务地址
    username: 3427160868@qq.com # 邮箱账号
    password: peeexdzfoxunchae # 授权码
    default-encoding: UTF-8
    #RabbitMq
  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: / # rabbitmq的虚拟host
    username: guest # rabbitmq的用户名
    password: guest # rabbitmq的密码
    #    publisher-confirms: true
    publisher-returns: true #如果对异步消息需要回调必须设置为true
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  #4.ES
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300 # es的连接地址及端口号
      cluster-name: elasticsearch # es集群的名称
  #5.redis
  redis:
    host: xiaoquan.work # Redis服务器地址
    database: 1 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: xiaoquan0810 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
#  main:
#    allow-bean-definition-overriding: true
logging:
  level:
    com:
      ihrm:
        company: debug
  file:
    path: ${user.dir}\log
#监控配置
info:
  app:
    user: ihrm
    version: 1.0.0
    test: test
management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        # 暴露的端口，默认只有health、info
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

